### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Jacqueries** [yassermb/DLA-Ranker#2]
Hello,
I tried to install the program from source code but I ran into some compatibility issues with tensorflow, cuda and cudnn (in my opinion, but the versions seem compatible here https://www.tensorflow.org/install/source#gpu). Using the requirements that you specified I end up having  an error when I run python test.py

`Traceback (most recent call last):
  File "test.py", line 90, in <module>
    model = load_model(path.join('../Models', 'BM5', '0_model'))
  File "/home/abbesses/grand/miniconda3/envs/dla-ranker/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 190, in load_model
    return saved_model_load.load(filepath, compile)
  File "/home/abbesses/grand/miniconda3/envs/dla-ranker/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 126, in load
    training_config))
  File "/home/abbesses/grand/miniconda3/envs/dla-ranker/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 230, in compile_args_from_training_config
    sample_weight_mode = training_config['sample_weight_mode']
KeyError: 'sample_weight_mode'
`
Also in the file DLA-ranker.yml a file requirements.txt is specified, do I need  to create it myself ? If so what should be its content ?
Can you provide a more detailed version of your environment with the exact version of tensorflow, cuda pytorch... used ? 
Many thanks

**Comment by yassermb** [comment]
Hello,
Thank you for using our tool. The model is trained using Tensorflow version 2.3. So I recommend that you use this version when you are testing it.

**Comment by Jacqueries** [comment]
Hello,
I used tensorflow 2.3 along with all other specified version but I get compatibility errors. Can you provide the details of the environment on wich you made DLA-Ranker runs and could you provide the file requirements.txt ?  

Also when I run python generate_cubes.py I get a lot of warnings and the folder ../Examples/map_dir does contain a folder 1AK4 with 1AK4/0 and 1AK4/1 but those are empty.

**Comment by gabrielctn** [comment]
Hi all,
After many hours of testing, I found that the issue is actually a problem due to GPU architecture incompatibility.
The tensorflow 2.3 package does not contain PTX code for Nvidia 3080 GPUs.
The error message obtained is
```python
>>> tf.test.is_gpu_available()
RuntimeError: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid
```
See https://www.tensorflow.org/install/gpu#hardware_requirements

I tried installing on a machine with a 1080 GPU and now it works.

@yassermb 
Here is the `DLA_ranker.yml` I used to make it work for information, because some dependencies were missing:
```yaml
name: dla_ranker

channels:
  - conda-forge
  - anaconda
  - pytorch

dependencies:
  - python=3.8
  - compilers
  - cudnn=7.6
  - cudatoolkit=10.1
  - cudatoolkit-dev=10.1
  - cupti=10.1
  - pytorch-gpu=1.7.1
  - torchvision=0.8.2
  - cmake
  - jupyterlab
  - mpi4py
  - nodejs
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - prody
  - lz4
  - pip
  - pip:
    - tensorflow-gpu==2.3
    - pypdb
    - ipython
  - bokeh
```
